version: '3.7'

services:
  grype-scanner:
    container_name: grype-scanner
    image: owenwilson/grype-tool-security:latest
    ports:
      - 9898:8000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      grype-net:

networks:
  grype-net:
